export PS1="$USER@`/bin/hostname -s`-> "  
export PGPORT=2012  
export PGDATA=/data/pgdata  
export LANG=en_US.utf8 
export VERSION=9.6 
export PGHOME=/opt/pgsql$VERSION  
export LD_LIBRARY_PATH=$PGHOME/lib:/lib:/usr/lib:/usr/local/lib  
export DATE=`date +"%Y%m%d%H%M"`  
export PATH=$PGHOME/bin:$PATH:.  
export MANPATH=$PGHOME/share/man:$MANPATH  
export PGHOST=$PGDATA  
export PGDATABASE=postgres  
export PGUSER=postgres  
alias rm='rm -i'  
