BEGIN;

CREATE ROLE "operator" WITH INHERIT LOGIN CREATEROLE CREATEDB REPLICATION ENCRYPTED PASSWORD '5302469' ; 
CREATE ROLE "repuser" WITH INHERIT LOGIN REPLICATION ENCRYPTED PASSWORD '119'; 
CREATE ROLE "leader" ; 
CREATE ROLE "worker" WITH INHERIT CREATEROLE CREATEDB  REPLICATION  ;
COMMIT;

CREATE DATABASE "HLD" WITH ENCODING=UTF8;

BEGIN;
ALTER DATABASE "HLD" OWNER TO "operator";
-- GRANT leader TO "operator" GRANTED BY "ComputerLover";
GRANT worker TO "operator" GRANTED BY "ComputerLover";
COMMIT;
