# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcessProduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladingbill',
            name='提单号',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
