# Generated by Django 2.2.1 on 2019-06-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcessProduction', '0004_auto_20170721_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('日期', models.DateField()),
                ('名称', models.CharField(max_length=32)),
                ('单位', models.CharField(blank=True, max_length=32)),
                ('数据', models.FloatField(null=True)),
                ('类别', models.CharField(max_length=32)),
                ('状态', models.CharField(max_length=32)),
                ('备注', models.TextField(blank=True)),
                ('月累', models.FloatField(null=True)),
                ('年累', models.FloatField(null=True)),
                ('数据源', models.TextField(blank=True)),
            ],
            options={
                'db_table': '生产信息',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('时间', models.DateTimeField()),
                ('名称', models.CharField(max_length=32)),
                ('单位', models.CharField(max_length=32)),
                ('数据', models.FloatField()),
                ('类别', models.CharField(max_length=32)),
                ('备注', models.TextField(blank=True)),
            ],
            options={
                'db_table': '生产动态',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='生产信息',
        ),
        migrations.DeleteModel(
            name='生产动态',
        ),
        migrations.AlterModelOptions(
            name='ladingbill',
            options={'managed': False},
        ),
    ]
