# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('位号', models.CharField(max_length=32)),
                ('名称', models.CharField(max_length=32)),
                ('备注', models.TextField(blank=True)),
            ],
            options={
                'db_table': '设备位号',
            },
        ),
    ]
