# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QHSE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='liaoDongPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('姓名', models.CharField(max_length=32)),
                ('电话', models.CharField(max_length=64)),
                ('手机', models.CharField(max_length=32)),
                ('电邮', models.CharField(max_length=32)),
                ('办公地点', models.CharField(max_length=32)),
                ('单位', models.CharField(max_length=32)),
                ('部门', models.CharField(max_length=32)),
                ('岗位', models.CharField(max_length=32)),
            ],
            options={
                'db_table': '通讯录',
            },
        ),
    ]
