BEGIN;
	CREATE ROLE "ComputerLover" LOGIN SUPERUSER CREATEDB CREATEROLE REPLICATION ENCRYPTED PASSWORD 'HLD^_^';
	CREATE ROLE "operator" LOGIN CREATEDB CREATEROLE REPLICATION ENCRYPTED PASSWORD '5302469';
	CREATE ROLE "repuser" LOGIN REPLICATION ENCRYPTED PASSWORD '119';
	
	CREATE ROLE "leader" ;
	CREATE ROLE "worker" WITH INHERIT CREATEROLE CREATEDB  REPLICATION  ;
	GRANT "worker" TO "operator" ; 
	
	CREATE DATABASE "HLD"  WITH OWNER = "operator" ENCODING = 'UTF8';
	CREATE DATABASE "test"  WITH OWNER = "operator" ENCODING = 'UTF8';
END;
